import Nav from "@/components/Nav";
import "./globals.css";

export const metadata = {
  title: "Users Data",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className="">
        <main className="h-fit max-w-[100vw] min-h-[100vh] bg-[#f5f6fa] overflow-hidden">
          <Nav />
          <section className="relative overflow-hidden">{children}</section>
          Footer
        </main>
      </body>
    </html>
  );
}
